name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0-dev.3028+a85495ca2

      - name: Run Tests
        run: zig build test

      - name: Build Contiguous Demo
        run: zig build demo-contiguous

      - name: Build Tree Demo
        run: zig build demo-tree

      - name: Build Docs
        run: zig build docs
